package org.example.logic.usecase

object ClothingWears {
    const val HEAVY_COAT = "heavy coat"
    const val SCARF = "scarf"
    const val GLOVES = "gloves"
    const val THERMAL_SHIRT = "thermal shirt"
    const val WARM_PANTS = "warm pants"
    const val WOOL_SOCKS = "wool socks"
    const val BOOTS = "boots"
    const val JACKET = "jacket"
    const val SWEATER = "sweater"
    const val LONG_PANTS = "long pants"
    const val CLOSED_SHOES = "closed shoes"
    const val LIGHT_JACKET = "light jacket"
    const val HOODIE = "hoodie"
    const val T_SHIRT = "t-shirt"
    const val JEANS = "jeans"
    const val SHORTS = "shorts"
    const val SANDALS = "sandals"
    const val SUNGLASSES = "sunglasses"
    const val SUN_HAT = "sun hat"
    const val UMBRELLA = "umbrella"
    const val RAINCOAT = "raincoat"
    const val WATERPROOF_SHOES = "waterproof shoes"
    const val WINDBREAKER = "windbreaker"
    const val BREATHABLE_FABRICS = "breathable fabrics"
    const val GYM_BAG = "gym bag"
    const val BUTTON_UP_SHIRT = "button-up shirt"
    const val SLACKS = "slacks"
    const val DRESS_SHOES = "dress shoes"
    const val SPORT_JACKET = "sport jacket"
    const val SNEAKERS = "sneakers"
    const val BLAZER = "blazer"
    const val CHINOS = "chinos"
    const val LOAFERS = "loafers"
    const val FLOWY_DRESS = "flowy dress"
    const val WIDE_BRIM_HAT = "wide-brim hat"
}